# Generated by Django 3.1.3 on 2021-01-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedIn',
            field=models.URLField(blank=True),
        ),
    ]
