# Generated by Django 3.1.3 on 2021-01-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendas',
            name='year',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
