# Generated by Django 3.1.3 on 2021-01-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agendas_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agendas',
            new_name='Agenda',
        ),
    ]
