# Generated by Django 3.1.3 on 2021-03-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210301_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='background',
            field=models.ImageField(default='', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image1',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image2',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
