# Generated by Django 3.1.3 on 2021-03-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20210301_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='background',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='quote',
        ),
    ]
