# Generated by Django 3.1.3 on 2021-03-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='introimage',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='shortTitle',
            field=models.CharField(default='', max_length=2000000000),
        ),
    ]
