# Generated by Django 3.1.3 on 2021-03-02 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('topicPref1', models.CharField(blank=True, choices=[(0, 'CLIMATE ACTION'), (1, 'FINANCIAL INDEPENDENCE OF WOMEN'), (2, 'RURAL ILLITERACY AND UNEMPLOYMENT'), (3, 'YOUTH PRIVACY AND SOCIAL MEDIA'), (4, 'ZERO HUNGER')], max_length=2000)),
                ('topicPref2', models.CharField(blank=True, choices=[(0, 'CLIMATE ACTION'), (1, 'FINANCIAL INDEPENDENCE OF WOMEN'), (2, 'RURAL ILLITERACY AND UNEMPLOYMENT'), (3, 'YOUTH PRIVACY AND SOCIAL MEDIA'), (4, 'ZERO HUNGER')], max_length=2000)),
                ('topicPref3', models.CharField(blank=True, choices=[(0, 'CLIMATE ACTION'), (1, 'FINANCIAL INDEPENDENCE OF WOMEN'), (2, 'RURAL ILLITERACY AND UNEMPLOYMENT'), (3, 'YOUTH PRIVACY AND SOCIAL MEDIA'), (4, 'ZERO HUNGER')], max_length=2000)),
                ('topicPref4', models.CharField(blank=True, choices=[(0, 'CLIMATE ACTION'), (1, 'FINANCIAL INDEPENDENCE OF WOMEN'), (2, 'RURAL ILLITERACY AND UNEMPLOYMENT'), (3, 'YOUTH PRIVACY AND SOCIAL MEDIA'), (4, 'ZERO HUNGER')], max_length=2000)),
                ('topicPref5', models.CharField(blank=True, choices=[(0, 'CLIMATE ACTION'), (1, 'FINANCIAL INDEPENDENCE OF WOMEN'), (2, 'RURAL ILLITERACY AND UNEMPLOYMENT'), (3, 'YOUTH PRIVACY AND SOCIAL MEDIA'), (4, 'ZERO HUNGER')], max_length=2000)),
                ('age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(21)])),
                ('schoolName', models.CharField(blank=True, max_length=1000)),
                ('courseName', models.CharField(blank=True, max_length=1000)),
                ('yearGrad', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(999), django.core.validators.MaxValueValidator(10000)])),
                ('city', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
