# Generated by Django 3.1.3 on 2021-03-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20210305_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegate',
            name='topicPref4',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='topicPref5',
        ),
        migrations.AlterField(
            model_name='delegate',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=200),
        ),
    ]
