# Generated by Django 3.1.3 on 2021-03-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210306_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='registeredBy',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='delegate',
            name='team',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
