# Generated by Django 3.1.3 on 2021-03-22 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20210313_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='timeRegistered',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
